# Generated by Django 4.0.3 on 2022-03-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pythonMyProject.bikes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('type', models.CharField(choices=[('Enduro', 'Enduro'), ('XC', 'XC'), ('Downhill', 'Downhill')], max_length=8)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
