# Generated by Django 4.0.3 on 2022-04-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pythonMyProject.bikes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikes', '0002_alter_bike_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('type', models.CharField(choices=[('Enduro', 'Enduro'), ('XC', 'XC'), ('Downhill', 'Downhill')], max_length=8)),
                ('fork', models.CharField(max_length=50, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('rear_shock', models.CharField(max_length=50, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('brakes', models.CharField(max_length=50, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('drivetrain', models.CharField(max_length=30, validators=[pythonMyProject.bikes.models.validate_letters_and_nums])),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
