# Generated by Django 4.0.3 on 2022-04-02 11:20

from django.db import migrations, models
import pythonMyProject.bikes.models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_sellbike'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbike',
            name='frame',
            field=models.CharField(default=1, max_length=30, validators=[pythonMyProject.bikes.models.validate_letters_and_nums]),
            preserve_default=False,
        ),
    ]
