# Generated by Django 4.0.3 on 2022-04-06 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_sellbike_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbike',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
