# Generated by Django 4.0.3 on 2022-04-06 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_sellbike_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
